services:
  gptapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: gpt-api-viewer:latest
    container_name: gpt-api
    ports:
      - "8003:8003"
    volumes:
      - ./cache:/app/cache
      - ./gpt_analysis:/app/gpt_analysis:ro
    networks:
      - model-network
    restart: unless-stopped

networks:
  model-network:
    external: true
